### ISSUE TITLE
Framework update for UL

### ISSUE THREAD

**Issue by hqucms** [hqucms/NanoHRT-tools#19]
**Development branch:** 
- https://github.com/hqucms/NanoHRT-tools/tree/dev/UL

**Todo:**
- [ ] Update [sample lists](https://github.com/hqucms/NanoHRT-tools/tree/dev/UL/run/samples) to [UL NanoV8](https://gitlab.cern.ch/cms-nanoAOD/nanoaod-doc/-/wikis/Releases/NanoAODv8)
    - [ ] Update xsecs if needed
- [ ] Adapt producers to UL NanoV8
    - [ ] update ParticleNet tagger names used in official Nano
    - [ ] retrain sfBDT: note SV in official Nano has preselection `dlenSig>3` ([link](https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/vertices_cff.py#L16))
    - [ ] ...?
- [ ] Update JEC/JERs

**Comment by hqucms** [comment]
@gouskos @pkontaxa @colizz
Feel free to add/edit/comment!

**Comment by gouskos** [comment]
> @gouskos @pkontaxa @colizz
> Feel free to add/edit/comment!

Thanks a lot @hqucms !
